services:
  front-end:
    container_name: frontend_portfolio
    build:
      context: ./portfolio
      target: production
    ports:
      - "127.0.0.1:10000:80"
    networks:
      - proxyNet

networks:
  proxyNet:
    external: true